package algorithms;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Fib {
	public static void main(String[] args) {
		int sum = 0;
		int i = 0;
		do {
			int v = solution(i);
			if (v % 2 == 0)
				sum += v;
			i += 1;
		} while (solution(i) < 4000000);

		System.out.println(sum);
	}

	private static int solution(int firsts) {
		if (firsts == 0)
			return 0;
		if (firsts == 1)
			return 1;
		else
			return solution(firsts - 1) + solution(firsts - 2);
	}
}
